### ISSUE TITLE
Fedora 29: app is launching but Start button does not do anything

### ISSUE THREAD

**Issue by VincentMarmiesse** [NicolasGuilloux/blade-shadow-beta#29]
**Describe the bug**
Hi,
First of all, thank you for your amazing work!
I have an issue when I use the app, it lauches fine but the orange button "Start" with the Shadow logo does not do anything.

**System**
 - OS: Fedora
 - OS Version: 29
 - Environment: Gnome
 - Application: AppImage
 - Application Version: 4.1.0

**Configuration**
 - The user is in input group ? yes
 - The environment uses Xorg ? How can I check this?
 - VA API detects H264 ? And H265 ? I'm not sure because I have this error:
```
$ vainfo
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

**To Reproduce**
1. Launch `./shadowbeta-linux-x86_64.AppImage`
2. Click on the "Start" button

**Additional context**
Here are my full logs:
```
$ ./shadowbeta-linux-x86_64.AppImage 
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `echo 01:00.0 VGA compatible controller: NVIDIA Corporation GP104GLM [Quadro P3200 Mobile] (rev a1)'
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

The website of the Shadow Linux community: https://nicolasguilloux.github.io/blade-shadow-beta

WARNING:
 • Your GPU brand is NVIDIA with less than the 1000 serie. We recommand you to use the Nouveau drivers instead of the NVIDIA drivers and install the NVIDIA firmware to attempt to improve VA API compatibility with your GPU (https://nouveau.freedesktop.org/wiki/VideoAcceleration/#firmware)
 • Your GPU is not recognized. Please check your hardware decoding drivers with the 'vainfo' command.

Hotkeys
    • lShift-lCtrl-Esc      Open the Windows task manager
    • lShift-lCtrl-Q        Stop the stream
    • lShift-lCtrl-F        Toggle fullscreen or windowed
    • lShift-lCtrl-G        Toggle input grab

Notes:
    • The H265 option is not enabled when the stream starts. Please enable it from the Shadow Control Panel on your Shadow.
    • Some devices crash the stream. During the fisrt install, make sure your only have the minimum devices plugged. Then, plug them one by one to identify quickly which one produces an error.

Checking for update
Found version 4.1.1 (url: Shadow Beta-4.1.1.AppImage)
Downloading update from Shadow Beta-4.1.1.AppImage
Error: Error: ENOENT: no such file or directory, open '/tmp/.mount_shadow9scbNY/opt/Shadow Beta/resources/app-update.yml'
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (webpack-internal:///522:411:19)
    at new PromiseSpawn (webpack-internal:///534:43:17)
    at eval (webpack-internal:///534:197:21)
    at AppImageUpdater.doCheckForUpdates (webpack-internal:///135:558:7)
    at AppImageUpdater.checkForUpdates (webpack-internal:///135:361:35)
    at UpdateService.eval (webpack-internal:///514:50:44)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///0:103:75)
    at new Promise (<anonymous>)
    at Object.__awaiter (webpack-internal:///0:99:16)
    at UpdateService.update (webpack-internal:///514:17:24)
    at UpdateService.startUpdate (webpack-internal:///514:14:21)
    at EventEmitter.electron_1.ipcMain.on (webpack-internal:///60:38:35)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/tmp/.mount_shadow9scbNY/opt/Shadow Beta/resources/electron.asar/browser/api/web-contents.js:343:13)
    at WebContents.emit (events.js:182:13)
Unhandled rejection Error: ENOENT: no such file or directory, open '/tmp/.mount_shadow9scbNY/opt/Shadow Beta/resources/app-update.yml'
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (webpack-internal:///522:411:19)
    at new PromiseSpawn (webpack-internal:///534:43:17)
    at eval (webpack-internal:///534:197:21)
    at AppImageUpdater.doCheckForUpdates (webpack-internal:///135:558:7)
    at AppImageUpdater.checkForUpdates (webpack-internal:///135:361:35)
    at UpdateService.eval (webpack-internal:///514:50:44)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///0:103:75)
    at new Promise (<anonymous>)
    at Object.__awaiter (webpack-internal:///0:99:16)
    at UpdateService.update (webpack-internal:///514:17:24)
    at UpdateService.startUpdate (webpack-internal:///514:14:21)
    at EventEmitter.electron_1.ipcMain.on (webpack-internal:///60:38:35)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/tmp/.mount_shadow9scbNY/opt/Shadow Beta/resources/electron.asar/browser/api/web-contents.js:343:13)
    at WebContents.emit (events.js:182:13)

(node:5134) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
and when I click on the "Start" button, theses lines appear in my terminal:

```
Censored
```

Thanks a lot for your help!

**Comment by b-lechalupe** [comment]
I have exactly the same problem here with my own Fedora 29. Everything was fine before the last update.

System

    OS: Fedora
    OS Version: 29
    Environment: Gnome
    Application: AppImage
    Application Version: 4.1.0

Configuration

    The user is in input group ? yes
    The environment uses Xorg ? yes
    VA API detects H264 ? yes, HEVC available as well

```
[benjamin@NB01 Shadow Beta]$ ./shadowbeta-linux-x86_64.AppImage 
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0

Le site de la communauté Shadow Linux: https://nicolasguilloux.github.io/blade-shadow-beta

Raccourcis
    • lShift-lCtrl-Esc      Ouvre le gestionnaire de tâches de Windows
    • lShift-lCtrl-Q        Arrête le stream
    • lShift-lCtrl-F        Activer/désactiver le mode plein écran
    • lShift-lCtrl-G        Activer/désactiver la capture du clavier et de la souris

Notes:
    • Le H265 ne s'active malheureusement pas au lancement du stream. Vérifiez dans l'application Shadow Control Panel sur votre Shadow s'il est bien activé.
    • Certains périphériques font planter le stream. Lors de la première installation, veillez à n'avoir que le strict minimum de brancher. Ensuite, brancher un à un chaque périphérique pour identifier si il y en a un qui provoque un crash.


(shadow-beta:6169): Gtk-WARNING **: 21:21:34.661: Theme parsing error: gtk.css:126:40: Expected ')' in color definition

(shadow-beta:6169): Gtk-WARNING **: 21:21:34.669: Theme parsing error: gtk.css:8687:128: Expected a valid selector
Checking for update
Found version 4.1.1 (url: Shadow Beta-4.1.1.AppImage)
Downloading update from Shadow Beta-4.1.1.AppImage
Error: Error: ENOENT: no such file or directory, open '/tmp/.mount_shadowse4Ubn/opt/Shadow Beta/resources/app-update.yml'
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (webpack-internal:///522:411:19)
    at new PromiseSpawn (webpack-internal:///534:43:17)
    at eval (webpack-internal:///534:197:21)
    at AppImageUpdater.doCheckForUpdates (webpack-internal:///135:558:7)
    at AppImageUpdater.checkForUpdates (webpack-internal:///135:361:35)
    at UpdateService.eval (webpack-internal:///514:50:44)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///0:103:75)
    at new Promise (<anonymous>)
    at Object.__awaiter (webpack-internal:///0:99:16)
    at UpdateService.update (webpack-internal:///514:17:24)
    at UpdateService.startUpdate (webpack-internal:///514:14:21)
    at EventEmitter.electron_1.ipcMain.on (webpack-internal:///60:38:35)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/tmp/.mount_shadowse4Ubn/opt/Shadow Beta/resources/electron.asar/browser/api/web-contents.js:343:13)
    at WebContents.emit (events.js:182:13)
Unhandled rejection Error: ENOENT: no such file or directory, open '/tmp/.mount_shadowse4Ubn/opt/Shadow Beta/resources/app-update.yml'
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (webpack-internal:///522:411:19)
    at new PromiseSpawn (webpack-internal:///534:43:17)
    at eval (webpack-internal:///534:197:21)
    at AppImageUpdater.doCheckForUpdates (webpack-internal:///135:558:7)
    at AppImageUpdater.checkForUpdates (webpack-internal:///135:361:35)
    at UpdateService.eval (webpack-internal:///514:50:44)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///0:103:75)
    at new Promise (<anonymous>)
    at Object.__awaiter (webpack-internal:///0:99:16)
    at UpdateService.update (webpack-internal:///514:17:24)
    at UpdateService.startUpdate (webpack-internal:///514:14:21)
    at EventEmitter.electron_1.ipcMain.on (webpack-internal:///60:38:35)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/tmp/.mount_shadowse4Ubn/opt/Shadow Beta/resources/electron.asar/browser/api/web-contents.js:343:13)
    at WebContents.emit (events.js:182:13)

(node:6169) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

```

**Comment by VincentMarmiesse** [comment]
@b-lechalupe, do you have Nvidia or Nouveau drivers? I currently have Nvidia ones and I'm afraid to uninstall them for Nouveau ones...

**Comment by NicolasGuilloux** [comment]
Hi guys!
I just edited your message as your token was visible. Please shutdown your Shadow (and I really mean shutdown the windows) because it is a security issue! Be careful about sharing something that mention `token`.

**Comment by NicolasGuilloux** [comment]
Vincent,
It appears that your card is not well detected by the VA API. What GPU brand do you have?

**Comment by VincentMarmiesse** [comment]
Hi Nicolas,
Thanks for your edit.
I have a Lenovo P52, and my GPU is an Nvidia Quadro P3200.

**Comment by VincentMarmiesse** [comment]
Ok so after some digging, I installed the `libva-vdpau-driver` package and I now have a correct output from `vainfo`:
```
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.4 (libva 2.4.0)
vainfo: Driver version: Splitted-Desktop Systems VDPAU backend for VA-API - 0.7.4
vainfo: Supported profile and entrypoints
VAProfileMPEG2Simple            :	VAEntrypointVLD
VAProfileMPEG2Main              :	VAEntrypointVLD
VAProfileMPEG4Simple            :	VAEntrypointVLD
VAProfileMPEG4AdvancedSimple    :	VAEntrypointVLD
<unknown profile>               :	VAEntrypointVLD
VAProfileH264Main               :	VAEntrypointVLD
VAProfileH264High               :	VAEntrypointVLD
VAProfileVC1Simple              :	VAEntrypointVLD
VAProfileVC1Main                :	VAEntrypointVLD
VAProfileVC1Advanced            :	VAEntrypointVLDAProfileH264Main
```

but I still have the same error.

**Comment by b-lechalupe** [comment]
Hello, I tried the new version 4.1.1. Still an issue with the new version : I can see the update to 4.1.1, then my shadow start (with the new UI), but nothing happen when clicking on the start button.

**Comment by Kabouik** [comment]
I am having the same issue with Solus 4.0, while the community Appimage file built by @Alex^ (on Discord) was working fine on the same system. There must be one or several libraries missing in the official Appimage supplied by Blade, making it compatible only with distributions that have these libraries anyway.

@Alex^says that in my case, the issue is presumably libsnd6.1, which seems to be required by libSDL2.0, while my distribution only provides libsdnio.so.7.0.

I filled a bug report on Discord to mention this issue and ask the developers to include the version 6.1 in the next Appimage. No feedback, but hopefully they will do it and it was the same issue for us all.

**Comment by aarnoud** [comment]
@VincentMarmiesse you need to check this : https://gitlab.com/aar642/libva-vdpau-driver

**Comment by aarnoud** [comment]
Quadro aren't working for now...

**Comment by aarnoud** [comment]
Most of the thread must be fixed today :

- Lack of va driver
- Unsupported NVIDIA card
- Old AppImage issues

Closing, feel free to open a new case, with more and fresh details if needed.
